"""
Vector store for semantic search using numpy-based cosine similarity.

Stores embeddings in SQLite as blobs and computes similarity in-memory.
For production scale, this would swap to FAISS or chromadb, but for
a local MCP server this is fast enough and dependency-light.
"""

from __future__ import annotations

import struct
from typing import Any

import numpy as np

from nexus_mcp.storage.database import Database


def _serialize_embedding(embedding: list[float]) -> bytes:
    """Pack a float list into compact bytes."""
    return struct.pack(f"{len(embedding)}f", *embedding)


def _deserialize_embedding(data: bytes) -> np.ndarray:
    """Unpack bytes back to numpy array."""
    n = len(data) // 4  # 4 bytes per float32
    return np.array(struct.unpack(f"{n}f", data), dtype=np.float32)


class VectorStore:
    """
    Semantic search over project content using cosine similarity.

    Embeddings are generated by the Ollama intelligence layer and stored
    in SQLite. Search computes cosine similarity across all stored vectors.
    """

    def __init__(self, db: Database):
        self._db = db

    async def store(
        self,
        source_type: str,
        source_id: int,
        chunk_text: str,
        embedding: list[float],
    ) -> None:
        """Store an embedding vector for a content chunk."""
        blob = _serialize_embedding(embedding)
        await self._db.store_embedding(source_type, source_id, chunk_text, blob)

    async def clear(self, source_type: str, source_id: int) -> None:
        """Remove all embeddings for a source."""
        await self._db.clear_embeddings(source_type, source_id)

    async def search(
        self,
        query_embedding: list[float],
        top_k: int = 10,
        min_similarity: float = 0.3,
    ) -> list[dict[str, Any]]:
        """
        Find the most similar content chunks to a query embedding.

        Returns list of dicts with keys: source_type, source_id, chunk_text, similarity
        """
        query_vec = np.array(query_embedding, dtype=np.float32)
        query_norm = np.linalg.norm(query_vec)
        if query_norm == 0:
            return []

        all_embeddings = await self._db.get_all_embeddings()
        if not all_embeddings:
            return []

        results = []
        for row in all_embeddings:
            stored_vec = _deserialize_embedding(row["embedding"])
            stored_norm = np.linalg.norm(stored_vec)
            if stored_norm == 0:
                continue

            # Cosine similarity
            similarity = float(np.dot(query_vec, stored_vec) / (query_norm * stored_norm))

            if similarity >= min_similarity:
                results.append({
                    "source_type": row["source_type"],
                    "source_id": row["source_id"],
                    "chunk_text": row["chunk_text"],
                    "similarity": round(similarity, 4),
                })

        # Sort by similarity descending
        results.sort(key=lambda x: x["similarity"], reverse=True)
        return results[:top_k]

    async def count(self) -> int:
        """Return total number of stored embeddings."""
        embeddings = await self._db.get_all_embeddings()
        return len(embeddings)
